### ISSUE TITLE
DC Electric Vehicle Charging

### ISSUE THREAD

**Issue by pamukcu09** [uhi22/pyPLC#19] opened 2023-11-15 11:10 UTC
Hi,

Does this project only allow reading data from the vehicle?

When I run this software with my PWM signal with 5% Duty ratio, can I switch it to State C for DC Charging? @uhi22

**Comment by uhi22** [comment] 2023-11-15 14:27
I understand you plan to use pyPLC as EVSE. In this case, the car will switch from StateB to StateC (see https://github.com/uhi22/pyPLC#example-flow checkpoint 550). The current experience is, that pyPLC is able to convince the car to close the contactors, so basically it is possible to really charge the vehicle, not only to read out data.
In case of more detailled questions, please always mention the checkpoint number in https://github.com/uhi22/pyPLC#example-flow , together with your expected behavior and the observed behavior.

**Comment by uhi22** [comment] 2024-01-19 14:01
Question seems to be answered. Closing.

**Closed by uhi22** 2024-01-19 14:01 UTC
